### ISSUE TITLE
Basic Timer functionality

### ISSUE THREAD

**Issue by RisabhKedai** [MeAssure/MeAssure#4]
### Summary

As a user, I should be able to start and stop the timer after opening the app. The timer should run continuously as long as the pause / stop is not pressed.

### Acceptance Criteria

- [ ] If I click start the timer should start
- [ ] If I click pause the timer should pause, if it is running
- [ ] If I click stop , it should stop and reset if the timer is running.

### Linked Issues

- [ ] [Task-1] (#5  ) Create a mock UI for the timer screen
- [ ] [Feature-1] (#1 )Display the timer on the front screen
- [ ] [Feature-2] (#3 ) Display the start / stop functionality
